version: '3.1'

services:
  e-signature:
    build:
      context: .
      dockerfile: ./apps/e-signature/Dockerfile
      target: development
    command: pnpm run start:dev e-signature
    # env_file:
      # - ./apps/e-signature/.env
    ports:
      - 8002:8002
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mailer:
    build:
      context: .
      dockerfile: ./apps/mailer/Dockerfile
      target: development
    command: pnpm run start:dev mailer
    # env_file:
      # - ./apps/mailer/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  notification:
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
      target: development
    command: pnpm run start:dev notification
    # env_file:
      # - ./apps/notification/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  rabbitmq:
    image: rabbitmq:4
